// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameMmActive = "mm_active"

// MmActive 活动表
type MmActive struct {
	ID         int32     `gorm:"column:id;primaryKey;autoIncrement:true" json:"id"`
	Name       string    `gorm:"column:name;not null;comment:活动名称" json:"name"`                         // 活动名称
	Type       int32     `gorm:"column:type;not null;comment:类型 1 秒杀 2 团购 3 百团大战" json:"type"`          // 类型 1 秒杀 2 团购 3 百团大战
	Desc       string    `gorm:"column:desc;comment:活动描述" json:"desc"`                                  // 活动描述
	StartTime  time.Time `gorm:"column:start_time;not null;comment:活动开始时间" json:"start_time"`           // 活动开始时间
	EndTime    time.Time `gorm:"column:end_time;not null;comment:活动结束时间" json:"end_time"`               // 活动结束时间
	Status     bool      `gorm:"column:status;not null;default:1;comment:状态： 0 删除  1 正常" json:"status"` // 状态： 0 删除  1 正常
	CreateTime time.Time `gorm:"column:create_time;comment:创建时间" json:"create_time"`                    // 创建时间
	UpdateTime time.Time `gorm:"column:update_time;comment:更新时间" json:"update_time"`                    // 更新时间
	DeleteTime time.Time `gorm:"column:delete_time;comment:删除时间" json:"delete_time"`                    // 删除时间
}

// TableName MmActive's table name
func (*MmActive) TableName() string {
	return TableNameMmActive
}
