// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameMmActiveCoupon = "mm_active_coupon"

// MmActiveCoupon 活动-优惠券表。因为优惠券里面可以指定哪些商品可以使用
type MmActiveCoupon struct {
	ID         int32     `gorm:"column:id;primaryKey;autoIncrement:true" json:"id"`
	ActiveID   int32     `gorm:"column:active_id;not null;comment:活动ID" json:"active_id"`               // 活动ID
	CouponID   int32     `gorm:"column:coupon_id;comment:优惠券ID" json:"coupon_id"`                       // 优惠券ID
	Status     bool      `gorm:"column:status;not null;default:1;comment:状态： 0 删除  1 正常" json:"status"` // 状态： 0 删除  1 正常
	CreateTime time.Time `gorm:"column:create_time;comment:创建时间" json:"create_time"`                    // 创建时间
	UpdateTime time.Time `gorm:"column:update_time;comment:更新时间" json:"update_time"`                    // 更新时间
	DeleteTime time.Time `gorm:"column:delete_time;comment:删除时间" json:"delete_time"`                    // 删除时间
}

// TableName MmActiveCoupon's table name
func (*MmActiveCoupon) TableName() string {
	return TableNameMmActiveCoupon
}
