// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameMmCategory = "mm_category"

// MmCategory 商品分类表
type MmCategory struct {
	ID         int32     `gorm:"column:id;primaryKey;autoIncrement:true" json:"id"`
	Name       string    `gorm:"column:name;not null" json:"name"`
	ParentID   int32     `gorm:"column:parent_id;not null" json:"parent_id"`
	Path       string    `gorm:"column:path;not null;comment:路径，所有上级" json:"path"`        // 路径，所有上级
	Status     int32     `gorm:"column:status;default:1;comment:1 正常 0 删除" json:"status"` // 1 正常 0 删除
	CreateTime time.Time `gorm:"column:create_time" json:"create_time"`
	UpdateTime time.Time `gorm:"column:update_time" json:"update_time"`
	DeleteTime time.Time `gorm:"column:delete_time" json:"delete_time"`
}

// TableName MmCategory's table name
func (*MmCategory) TableName() string {
	return TableNameMmCategory
}
