// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameMmCouponUsageScope = "mm_coupon_usage_scope"

// MmCouponUsageScope 优惠券使用范围字典表
type MmCouponUsageScope struct {
	ID          int32     `gorm:"column:id;primaryKey;comment:使用范围ID" json:"id"`                   // 使用范围ID
	Code        string    `gorm:"column:code;not null;comment:英文标识，例如 platform、store" json:"code"` // 英文标识，例如 platform、store
	Name        string    `gorm:"column:name;not null;comment:使用范围名称" json:"name"`                 // 使用范围名称
	Description string    `gorm:"column:description;comment:描述（例如说明适用条件）" json:"description"`      // 描述（例如说明适用条件）
	CreateTime  time.Time `gorm:"column:create_time;default:CURRENT_TIMESTAMP" json:"create_time"`
	UpdateTime  time.Time `gorm:"column:update_time;default:CURRENT_TIMESTAMP" json:"update_time"`
}

// TableName MmCouponUsageScope's table name
func (*MmCouponUsageScope) TableName() string {
	return TableNameMmCouponUsageScope
}
