// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameMmMenu = "mm_menu"

// MmMenu 菜单
type MmMenu struct {
	ID         int32     `gorm:"column:id;primaryKey;autoIncrement:true" json:"id"`
	Name       string    `gorm:"column:name;comment:菜单名称" json:"name"`           // 菜单名称
	ParentID   int32     `gorm:"column:parent_id;comment:父级id" json:"parent_id"` // 父级id
	OrderNum   int32     `gorm:"column:order_num;comment:排序" json:"order_num"`   // 排序
	Component  string    `gorm:"column:component;comment:路径" json:"component"`   // 路径
	Status     int32     `gorm:"column:status;comment:状态1正常0禁用" json:"status"`   // 状态1正常0禁用
	CreateTime time.Time `gorm:"column:create_time" json:"create_time"`
	UpdateTime time.Time `gorm:"column:update_time" json:"update_time"`
}

// TableName MmMenu's table name
func (*MmMenu) TableName() string {
	return TableNameMmMenu
}
