// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameMmOrderPaidLog = "mm_order_paid_log"

// MmOrderPaidLog mapped from table <mm_order_paid_log>
type MmOrderPaidLog struct {
	ID        int32     `gorm:"column:id;primaryKey;autoIncrement:true" json:"id"`
	OrderID   int32     `gorm:"column:order_id;not null" json:"order_id"`
	OrderCode string    `gorm:"column:order_code" json:"order_code"`
	UserID    int32     `gorm:"column:user_id;not null" json:"user_id"`
	PaidPrice int32     `gorm:"column:paid_price;not null" json:"paid_price"`
	PaidAt    time.Time `gorm:"column:paid_at" json:"paid_at"`
}

// TableName MmOrderPaidLog's table name
func (*MmOrderPaidLog) TableName() string {
	return TableNameMmOrderPaidLog
}
