// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameMmOrderPayLog = "mm_order_pay_log"

// MmOrderPayLog 订单支付记录
type MmOrderPayLog struct {
	ID             int32     `gorm:"column:id;primaryKey;autoIncrement:true" json:"id"`
	OrderID        int32     `gorm:"column:order_id;not null;comment:订单id" json:"order_id"`   // 订单id
	OrderCode      string    `gorm:"column:order_code;comment:订单唯一编号" json:"order_code"`      // 订单唯一编号
	BatchCode      string    `gorm:"column:batch_code;comment:合单支付对应的code" json:"batch_code"` // 合单支付对应的code
	UserID         int32     `gorm:"column:user_id;not null" json:"user_id"`
	PayAmount      int64     `gorm:"column:pay_amount;not null" json:"pay_amount"`
	PayWay         int32     `gorm:"column:pay_way;comment:支付方式" json:"pay_way"`                      // 支付方式
	ThirdPartyCode string    `gorm:"column:third_party_code;comment:第三方订单编号" json:"third_party_code"` // 第三方订单编号
	PayQueryData   string    `gorm:"column:pay_query_data;comment:请求支付时的请求数据" json:"pay_query_data"`  // 请求支付时的请求数据
	PayTime        time.Time `gorm:"column:pay_time" json:"pay_time"`
}

// TableName MmOrderPayLog's table name
func (*MmOrderPayLog) TableName() string {
	return TableNameMmOrderPayLog
}
