// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameMmOrderCancelLog = "mm_order_cancel_log"

// MmOrderCancelLog 订单退款记录
type MmOrderCancelLog struct {
	ID          int32     `gorm:"column:id;primaryKey;autoIncrement:true" json:"id"`
	OrderID     int32     `gorm:"column:order_id;not null" json:"order_id"`
	OrderCode   string    `gorm:"column:order_code" json:"order_code"`
	UserID      int32     `gorm:"column:user_id;not null" json:"user_id"`
	CancelPrice int32     `gorm:"column:cancel_price;not null" json:"cancel_price"`
	CancelAt    time.Time `gorm:"column:cancel_at" json:"cancel_at"`
}

// TableName MmOrderCancelLog's table name
func (*MmOrderCancelLog) TableName() string {
	return TableNameMmOrderCancelLog
}
