// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameMmOrderSpu = "mm_order_spu"

// MmOrderSpu  订单-商品表：拆分订单商品具体到每一个规格（和order不同的是，order里面同一个商户的多个商品是一条数据，靠这里的拆分实现细化）
type MmOrderSpu struct {
	ID         int32  `gorm:"column:id;primaryKey;autoIncrement:true" json:"id"`
	OrderID    int32  `gorm:"column:order_id;not null;comment:订单id" json:"order_id"`             // 订单id
	OrderCode  string `gorm:"column:order_code;not null;comment:订单唯一标识。1 对 多" json:"order_code"` // 订单唯一标识。1 对 多
	UserID     int32  `gorm:"column:user_id;not null;comment:用户ID" json:"user_id"`               // 用户ID
	SpuID      int64  `gorm:"column:spu_id;not null;comment:商品id" json:"spu_id"`                 // 商品id
	SkuID      int64  `gorm:"column:sku_id;comment:规格id" json:"sku_id"`                          // 规格id
	UnitAmount int64  `gorm:"column:unit_amount;comment:单价 * 100" json:"unit_amount"`            // 单价 * 100
	Count      int32  `gorm:"column:count;comment:购买数量" json:"count"`                            // 购买数量
	/*
		订单支付状态：
		1. 待支付
		2. 已支付
		3. 部分退款成功
		4. 全额退款成功
		5. 部分申请退款中
		6. 全额申请退款中
	*/
	PaymentStatus int32 `gorm:"column:payment_status;comment:订单支付状态：\n1. 待支付\n2. 已支付\n3. 部分退款成功\n4. 全额退款成功\n5. 部分申请退款中\n6. 全额申请退款中" json:"payment_status"`
	/*
		支付方式：
		1. 微信支付
		2. 支付宝支付
		3. 银行卡支付
		...
	*/
	PaymentWay   int32     `gorm:"column:payment_way;comment:支付方式：\n1. 微信支付 \n2. 支付宝支付 \n3. 银行卡支付\n..." json:"payment_way"`
	TotalAmount  int64     `gorm:"column:total_amount;comment:总金额" json:"total_amount"`     // 总金额
	PayAmount    int64     `gorm:"column:pay_amount;comment:实际支付金额" json:"pay_amount"`      // 实际支付金额
	RefundAmount int64     `gorm:"column:refund_amount;comment:退款金额" json:"refund_amount"`  // 退款金额
	Specs        string    `gorm:"column:specs;not null;comment:规格合集，有问题的时候看" json:"specs"` // 规格合集，有问题的时候看
	IsSign       int32     `gorm:"column:is_sign;comment:是否签收" json:"is_sign"`              // 是否签收
	SignDate     time.Time `gorm:"column:sign_date;comment:签收时间-7天自动签收" json:"sign_date"`   // 签收时间-7天自动签收
	Status       bool      `gorm:"column:status;default:1;comment:默认启用吧" json:"status"`     // 默认启用吧
	CreateTime   time.Time `gorm:"column:create_time" json:"create_time"`
	UpdateTime   time.Time `gorm:"column:update_time" json:"update_time"`
}

// TableName MmOrderSpu's table name
func (*MmOrderSpu) TableName() string {
	return TableNameMmOrderSpu
}
