// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameMmPower = "mm_power"

// MmPower 权限表，包括菜单和路由
type MmPower struct {
	ID         int32     `gorm:"column:id;primaryKey;autoIncrement:true" json:"id"`
	Name       string    `gorm:"column:name;not null;comment:权限名/菜单名" json:"name"`                // 权限名/菜单名
	Route      string    `gorm:"column:route;not null;comment:路由" json:"route"`                   // 路由
	ParentID   int32     `gorm:"column:parent_id;not null;comment:父级，0则表示处于最顶层" json:"parent_id"` // 父级，0则表示处于最顶层
	Path       string    `gorm:"column:path;comment:保存所有上级" json:"path"`                          // 保存所有上级
	IsMenu     int32     `gorm:"column:is_menu;comment:是否是菜单" json:"is_menu"`                     // 是否是菜单
	Status     bool      `gorm:"column:status;not null;default:1" json:"status"`
	CreateTime time.Time `gorm:"column:create_time" json:"create_time"`
	UpdateTime time.Time `gorm:"column:update_time" json:"update_time"`
	DeleteTime time.Time `gorm:"column:delete_time" json:"delete_time"`
}

// TableName MmPower's table name
func (*MmPower) TableName() string {
	return TableNameMmPower
}
