// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

const TableNameMmRoleMenu = "mm_role_menu"

// MmRoleMenu 角色权限表
type MmRoleMenu struct {
	ID     int32 `gorm:"column:id;primaryKey;autoIncrement:true" json:"id"`
	RoleID int32 `gorm:"column:role_id" json:"role_id"`
	MenuID int32 `gorm:"column:menu_id" json:"menu_id"`
}

// TableName MmRoleMenu's table name
func (*MmRoleMenu) TableName() string {
	return TableNameMmRoleMenu
}
