// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameMmSpu = "mm_spu"

// MmSpu 商品表。包含商品 的基本信息
type MmSpu struct {
	ID         int32     `gorm:"column:id;primaryKey;autoIncrement:true" json:"id"`
	Name       string    `gorm:"column:name;not null;comment:商品名字" json:"name"`                 // 商品名字
	Desc       string    `gorm:"column:desc;comment:描述" json:"desc"`                            // 描述
	Imgs       string    `gorm:"column:imgs;comment:商品图片" json:"imgs"`                          // 商品图片
	BrandID    string    `gorm:"column:brand_id;not null;comment:所属品牌 // TODO" json:"brand_id"` // 所属品牌 // TODO
	CategoryID string    `gorm:"column:category_id;not null;comment:商品分类" json:"category_id"`   // 商品分类
	MerchantID int32     `gorm:"column:merchant_id;not null;comment:所属商户" json:"merchant_id"`   // 所属商户
	Status     bool      `gorm:"column:status;default:1;comment:1 正常 0 删除" json:"status"`       // 1 正常 0 删除
	CreateTime time.Time `gorm:"column:create_time" json:"create_time"`
	UpdateTime time.Time `gorm:"column:update_time" json:"update_time"`
	DeleteTime time.Time `gorm:"column:delete_time" json:"delete_time"`
}

// TableName MmSpu's table name
func (*MmSpu) TableName() string {
	return TableNameMmSpu
}
