// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameMmSpecKey = "mm_spec_key"

// MmSpecKey 规格表，保存通用规格信息，详细的规格信息以及价格等拆分到了spec
type MmSpecKey struct {
	ID         int32     `gorm:"column:id;primaryKey;autoIncrement:true" json:"id"`
	Name       string    `gorm:"column:name;not null;comment:规格名称" json:"name"`       // 规格名称
	Unit       string    `gorm:"column:unit;not null;comment:单位，比如条，张，台" json:"unit"` // 单位，比如条，张，台
	Status     bool      `gorm:"column:status;not null;default:1" json:"status"`
	CreateTime time.Time `gorm:"column:create_time" json:"create_time"`
	UpdateTime time.Time `gorm:"column:update_time" json:"update_time"`
	DeleteTime time.Time `gorm:"column:delete_time" json:"delete_time"`
}

// TableName MmSpecKey's table name
func (*MmSpecKey) TableName() string {
	return TableNameMmSpecKey
}
