// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameMmSubOrder = "mm_sub_order"

// MmSubOrder 子订单表 -- 由 mm_order拆分
type MmSubOrder struct {
	ID              int32     `gorm:"column:id;primaryKey;autoIncrement:true" json:"id"`
	OrderCode       string    `gorm:"column:order_code;not null;comment:订单唯一标识" json:"order_code"`                                 // 订单唯一标识
	OrderUniqueCode string    `gorm:"column:order_unique_code;not null;comment:订单唯一标识--区分每个子订单" json:"order_unique_code"`          // 订单唯一标识--区分每个子订单
	SpuID           int32     `gorm:"column:spu_id;not null;comment:商品ID" json:"spu_id"`                                           // 商品ID
	SkuID           int32     `gorm:"column:sku_id;not null;comment:规格ID" json:"sku_id"`                                           // 规格ID
	Nums            int32     `gorm:"column:nums;not null;comment:购买数量" json:"nums"`                                               // 购买数量
	OriginalPrice   int32     `gorm:"column:original_price;not null;comment:原价 * 100" json:"original_price"`                       // 原价 * 100
	FinalPrice      int32     `gorm:"column:final_price;not null;comment:最终价格 * 100" json:"final_price"`                           // 最终价格 * 100
	AddressID       int32     `gorm:"column:address_id;not null;comment:收货地址" json:"address_id"`                                   // 收货地址
	CouponID        int32     `gorm:"column:coupon_id;comment:优惠券" json:"coupon_id"`                                               // 优惠券
	PaymentStatus   int32     `gorm:"column:payment_status;comment:是否支付" json:"payment_status"`                                    // 是否支付
	PaymentWay      int32     `gorm:"column:payment_way;comment:支付方式：wx_pay 996 ali_pay 700 card_pay 789 ...." json:"payment_way"` // 支付方式：wx_pay 996 ali_pay 700 card_pay 789 ....
	IsSign          int32     `gorm:"column:is_sign;comment:是否签收" json:"is_sign"`                                                  // 是否签收
	SignDate        time.Time `gorm:"column:sign_date;comment:签收时间-7天自动签收" json:"sign_date"`                                       // 签收时间-7天自动签收
	Status          bool      `gorm:"column:status;default:1;comment:默认启用吧" json:"status"`                                         // 默认启用吧
	CreateTime      time.Time `gorm:"column:create_time" json:"create_time"`
	UpdateTime      time.Time `gorm:"column:update_time" json:"update_time"`
	DeleteTime      time.Time `gorm:"column:delete_time" json:"delete_time"`
}

// TableName MmSubOrder's table name
func (*MmSubOrder) TableName() string {
	return TableNameMmSubOrder
}
