// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameMmSpec = "mm_spec"

// MmSpec  规格详细表- 保存规格的详细信息
type MmSpec struct {
	ID         int32     `gorm:"column:id;primaryKey;autoIncrement:true" json:"id"`
	SkuID      int32     `gorm:"column:sku_id;not null;comment:商品ID" json:"sku_id"` // 商品ID
	Name       string    `gorm:"column:name;not null;comment:规格名称" json:"name"`     // 规格名称
	Price      int32     `gorm:"column:price;comment:price * 100" json:"price"`     // price * 100
	Strock     int32     `gorm:"column:strock;comment:商品库存" json:"strock"`          // 商品库存
	Status     int32     `gorm:"column:status;not null;default:1" json:"status"`
	CreateTime time.Time `gorm:"column:create_time" json:"create_time"`
	UpdateTime time.Time `gorm:"column:update_time" json:"update_time"`
	DeleteTime time.Time `gorm:"column:delete_time" json:"delete_time"`
}

// TableName MmSpec's table name
func (*MmSpec) TableName() string {
	return TableNameMmSpec
}
