// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameMmSpecValue = "mm_spec_value"

// MmSpecValue  规格详细表- 保存规格的详细信息
type MmSpecValue struct {
	ID         int32     `gorm:"column:id;primaryKey;autoIncrement:true" json:"id"`
	SpecID     int32     `gorm:"column:spec_id;not null;comment:商品ID" json:"spec_id"` // 商品ID
	Name       string    `gorm:"column:name;not null;comment:规格名称" json:"name"`       // 规格名称
	Status     bool      `gorm:"column:status;not null;default:1" json:"status"`
	CreateTime time.Time `gorm:"column:create_time" json:"create_time"`
	UpdateTime time.Time `gorm:"column:update_time" json:"update_time"`
	DeleteTime time.Time `gorm:"column:delete_time" json:"delete_time"`
}

// TableName MmSpecValue's table name
func (*MmSpecValue) TableName() string {
	return TableNameMmSpecValue
}
