// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameMmSeckillLog = "mm_seckill_log"

// MmSeckillLog mapped from table <mm_seckill_log>
type MmSeckillLog struct {
	ID         int32     `gorm:"column:id;primaryKey;autoIncrement:true" json:"id"`
	ActiveID   int32     `gorm:"column:active_id;not null" json:"active_id"`
	ActiveType int32     `gorm:"column:active_type;not null;comment:1 秒杀 2 ..." json:"active_type"` // 1 秒杀 2 ...
	SkuID      int32     `gorm:"column:sku_id" json:"sku_id"`
	UserID     int32     `gorm:"column:user_id" json:"user_id"`
	CreateAt   time.Time `gorm:"column:create_at" json:"create_at"`
}

// TableName MmSeckillLog's table name
func (*MmSeckillLog) TableName() string {
	return TableNameMmSeckillLog
}
